version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_container
    ports:
      - "8040:8040"
    volumes:
      - .:/django_celery
    command: python manage.py runserver 0.0.0.0:8040
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/django_celery
    depends_on:
      - django
      - redis

  redis:
    image: redis
